In [3]:
import os
import matplotlib.pyplot as plt
import sys
sys.executable


import tensorflow as tf


In [14]:
print("version",tf.__version__)

version 2.14.0


In [27]:
train_dataset_url = "https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv"
train_dataset_fp = tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),origin=train_dataset_url)
print("local copy on ",train_dataset_fp)
!head -n5 {train_dataset_fp}

local copy on  /home/tioner/.keras/datasets/iris_training.csv
120,4,setosa,versicolor,virginica
6.4,2.8,5.6,2.2,2
5.0,2.3,3.3,1.0,1
4.9,2.5,4.5,1.7,2
4.9,3.1,1.5,0.1,0


In [28]:
columns_names = ["sepal_length","sepal_width","petal length","petal_width","species"]
features_names = columns_names[:-1]
label_name = columns_names[-1]
class_names = ["iris setosa","iris versicolor","iris virginica"]
print("features",features_names)
print("tags",label_name)



features ['sepal_length', 'sepal_width', 'petal length', 'petal_width']
tags species


In [29]:
batch_size = 32
train_dataset = tf.data.experimental.make_csv_dataset(
    train_dataset_fp,
    batch_size,
    column_names = columns_names,
    label_name=label_name,
    num_epochs=1)
train_dataset

<_PrefetchDataset element_spec=(OrderedDict([('sepal_length', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('sepal_width', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('petal length', TensorSpec(shape=(None,), dtype=tf.float32, name=None)), ('petal_width', TensorSpec(shape=(None,), dtype=tf.float32, name=None))]), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [30]:
features ,label = next(iter(train_dataset))
print(features)

OrderedDict([('sepal_length', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([6.7, 5. , 7.7, 5. , 6.2, 5.7, 5.2, 6.5, 6.4, 5.2, 7.7, 4.7, 6.8,
       6.9, 4.6, 6. , 4.5, 5.5, 7.7, 6.4, 5.6, 5.4, 4.9, 4.9, 5.8, 6.7,
       5.8, 6.4, 4.4, 6.2, 6.4, 5.8], dtype=float32)>), ('sepal_width', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([3.3, 3.6, 3.8, 3.5, 2.2, 4.4, 3.5, 3. , 3.2, 3.4, 2.6, 3.2, 3.2,
       3.2, 3.1, 2.7, 2.3, 2.6, 3. , 2.7, 2.7, 3.7, 2.5, 3.1, 2.7, 3. ,
       2.7, 2.8, 3.2, 3.4, 2.8, 2.7], dtype=float32)>), ('petal length', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([5.7, 1.4, 6.7, 1.6, 4.5, 1.5, 1.5, 5.8, 5.3, 1.4, 6.9, 1.3, 5.9,
       5.7, 1.5, 5.1, 1.3, 4.4, 6.1, 5.3, 4.2, 1.5, 4.5, 1.5, 4.1, 5. ,
       5.1, 5.6, 1.3, 5.4, 5.6, 5.1], dtype=float32)>), ('petal_width', <tf.Tensor: shape=(32,), dtype=float32, numpy=
array([2.1, 0.2, 2.2, 0.6, 1.5, 0.4, 0.2, 2.2, 2.3, 0.2, 2.3, 0.2, 2.3,
       2.3, 0.2, 1.6, 0.3, 1.2, 2.3, 1.9, 1.3, 0.2, 1.7, 0.1,

In [33]:
def pack_features_vector(features,labels):
    """pack into single array"""
    feat =tfstack(list(features.values()),axis=1)
    return feats,labels

In [34]:
train_dataset = train_dataset.map(pack_features_vector)

NameError: in user code:

    File "/tmp/ipykernel_360076/1632540239.py", line 3, in pack_features_vector  *
        feat =tfstack(list(features.values()),axis=1)

    NameError: name 'tfstack' is not defined
